services:
  php-fpm:
    build:
      context: ./docker/images/php-fpm
    image: php-fpm
    depends_on:
      - mariadb
      - redis
      - beanstalkd
    container_name: php-fpm
    tty: true
    volumes:
      - ./codebases/hyperwaiver:/var/www/hyperwaiver
    network_mode: "host" 

  queue-worker:
    image: php-fpm
    container_name: queue-worker
    depends_on:
      - php-fpm
    tty: true
    environment:
      SERVICE_NAME: queue-worker
    working_dir: /var/www/hyperwaiver
    volumes:
      - ./codebases/hyperwaiver:/var/www/hyperwaiver
    command: php artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600
    restart: always 
    network_mode: "host" 
    
  scheduler-worker:
    image: php-fpm
    container_name: scheduler-worker
    depends_on:
      - php-fpm
    tty: true
    environment:
      SERVICE_NAME: scheduler-worker
    working_dir: /var/www/hyperwaiver
    volumes:
      - ./codebases/hyperwaiver:/var/www/hyperwaiver
    command: php artisan schedule:work
    restart: always 
    network_mode: "host" 

  mariadb:
    build:
      context: ./docker/images/mariadb
    image: mariadb
    container_name: mariadb
    tty: true
    volumes:
      - /mnt/docker-data:/var/lib/mysql
      - ./docker/images/mariadb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    network_mode: "host" 

  redis:
    build:
      context: ./docker/images/redis
    image: redis
    container_name: redis
    tty: true
    network_mode: "host" 

  beanstalkd:
    image: schickling/beanstalkd
    container_name: beanstalkd
    network_mode: "host" 

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
