services:
  caddy:
    build:
      context: ./docker/images/caddy
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config
      - ./docker/images/caddy/conf.d:/etc/caddy
      - ./codebases:/var/www
    environment:
      CF_ZONE_ID: ${CF_ZONE_ID}
      CF_API_KEY: ${CF_API_KEY}
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
    networks:
      web-network: